### ISSUE TITLE
To-Do list

### ISSUE THREAD

**Issue by T3Chnological** [PureProductions/mcpeserverdevaccess#1]
[APK release] (https://github.com/PureProductions/mcpeserverdevaccess/releases)

- [x] Open server
- [x] Release apk file
- [ ] Make it public << You won't be able to access the server yet
- [ ] Available on android
- [ ] Available on ios
- [ ] Out of development
- [ ] Release

**Comment by UltimateMcraft** [comment]
@T3Chnological is my alt account
